[package]
name = "filelock"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fs2 = { version = "0.4.3" }
log = "0.4.7"
flexi_logger = {version="0.22.5",features=["use_chrono_for_offset"]}
